spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/rag_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: 9c2b8f7d5a4e3c1f0a6b7d8e9f1234567a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d
  expiration: 86400000

minio:
  url: http://minio:9000

fastapi:
  url: http://fastapi:8000